services:
  - type: web
    name: chill-zone-backend
    env: node
    rootDir: backend
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
